### ISSUE TITLE
Weird behavior 

### ISSUE THREAD

**Issue by vinnik-dmitry07** [cubao/concave_hull#27]
![image](https://github.com/user-attachments/assets/d28d8bd1-cce8-4023-92f5-996d4ebff9e6)

It seems something was broken in versions >=0.0.6.
I tried prebuilt pypi, and also built from the github repo -- neither works.

**Comment by district10** [comment]
Thanks for reporting this. I tried to reproduce and it just crashed... (0.0.8). 0.0.6 and 0.0.7 works for me. I'll have a look.

**Comment by district10** [comment]
@vinnik-dmitry07 Are you using macos m1? I found a weird `std::sort` behavior on my mac (cause segment fault). I guess there's something wrong with compiler or m1-chip.

**Comment by bobyard-com** [comment]
Windows, Intel processor.

**Comment by vinnik-dmitry07** [comment]
Windows, an Intel processor.

**Comment by district10** [comment]
There is a problem in src/convex_hull.hpp/`std::sort(index.begin(), index.end(), [&](int i, int j)`. It should be https://en.wikipedia.org/wiki/Weak_ordering#Strict_weak_orderings
But it's not geometrically robust now (I'm not quite sure). I'm trying to solve this.

**Comment by district10** [comment]
The integrated convex hull is buggy (seems only on windows and macOS). Should be fixed in https://github.com/cubao/concave_hull/pull/28

**Comment by vinnik-dmitry07** [comment]
Fixed

**Comment by district10** [comment]
Released 0.0.9.
